version: '2'
services:
    unix_alpine:
        build: agents/unix_alpine/.
            # build: agents/unix_centos/.
        environment:
            - cp=192.168.150.128:2217
            - system=AUTOMIC
            - prefix=alpine
# For agents with smgr
#  unix_alpine:
#    build: agents/unix_alpine_w_smgr/.
#    environment:
#      - cp=192.168.150.128:2217
#      - system=AUTOMIC
#      - prefix=alpine
